name: Push Backend to AWS ECR

on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed] 
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ygo-backend
        IMAGE_TAG: ${{ github.sha }}
        DATABASE_URL: mysql+pymysql://admin:Playstation2002@ygo-db-instance.c1s8k8cm6rjh.eu-north-1.rds.amazonaws.com/ygo_db
        SECRET_KEY: 3f0afcde0e5093d46868403ab5c4eeddf1dd481277cc547b517582972966c5f0
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

    - name: Build, tag, and push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ygo-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
    - name: Deploy to ECS
      run: |
        # 1. Get the current task definition
        TASK_DEF=$(aws ecs describe-task-definition --task-definition ygo-backend)
        
        # 2. Create a new revision with the NEW image tag
        NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
          '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
        
        # 3. Register the new revision
        NEW_REVISION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEF" --query "taskDefinition.taskDefinitionArn" --output text)
        aws ecs update-service --cluster ygo-cluster --service ygowebapp-service-4pntnyu7 --task-definition $NEW_REVISION --force-new-deployment
    
    