name: Push Backend to AWS ECR

on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed] 
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ygo-backend
        IMAGE_TAG: ${{ github.sha }}
        DATABASE_URL: mysql+pymysql://admin:Playstation2002@ygo-db-instance.c1s8k8cm6rjh.eu-north-1.rds.amazonaws.com/ygo_db
        SECRET_KEY: 3f0afcde0e5093d46868403ab5c4eeddf1dd481277cc547b517582972966c5f0
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

    - name: Build, tag, and push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ygo-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ygo-cluster --service ygowebapp-service-4pntnyu7 --force-new-deployment
    
    - name: Get Backend Public IP
      id: get-ip
      run: |
        # Get the Task ARN
        TASK_ARN=$(aws ecs list-tasks --cluster ygo-cluster --service ygowebapp-service-4pntnyu7 --query "taskArns[0]" --output text)
        
        # Get the Public IP from the Network Interface
        ENI_ID=$(aws ecs describe-tasks --cluster ygo-cluster --tasks $TASK_ARN --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" --output text)
        PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query "NetworkInterfaces[0].Association.PublicIp" --output text)
        echo "ip=$PUBLIC_IP" >> $GITHUB_OUTPUT